server:
  port: 8081
spring:
  application:
    name: sports
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.242.14:3306/sport_homework?serverTimezone=GMT%2B8
    username: jcheng
    password: 178044


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql #设置sql语言
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true

